
CREATE TABLE IF NOT EXISTS students (
    student_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS teachers (
    teacher_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS courses (
    course_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name varchar(255) NOT NULL,
    teacher_id int NOT NULL,
    FOREIGN KEY(teacher_id) REFERENCES teachers(teacher_id)
);

CREATE TABLE IF NOT EXISTS enrollments (
    student_id int REFERENCES students(student_id),
    course_id int REFERENCES courses(course_id),
    PRIMARY KEY(student_id, course_id)
);

CREATE TABLE IF NOT EXISTS attendance (
    student_id int REFERENCES students(student_id),
    course_id int REFERENCES courses(course_id),
    date DATE,
    is_present BOOLEAN NOT NULL,
    PRIMARY KEY(student_id, course_id, date)
);

CREATE TABLE IF NOT EXISTS grades (
    student_id int REFERENCES students(student_id),
    course_id int REFERENCES courses(course_id),
    grade DOUBLE PRECISION NOT NULL,
    date DATE,
    PRIMARY KEY(student_id, course_id, date)
);